name: Test

on: 
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Pull and run Docker image
      run: |
        docker pull tejaswijosyula/cicdassignment:latest
        docker run --name model_test tejaswijosyula/cicdassignment:latest
    - name: Check test output
      run: |
        output=$(docker logs model_test)
        echo "$output"
        if [[ "$output" < *"Score: 0.35"* ]]; then
          exit 0
        else
          exit 1
        fi
