name: Test

on:
  pull_request:
    branches: [main]

  workflow_run:
    workflows: ["Train"]
    types: 
    - completed
  



jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull and run the Docker image, check for score
      run: |
        score=$(docker run tejaswijosyula/cicdassignment:latest | tail -n 1)
        echo "Score output: $score"
        # The last line of our output and is our score
        if (( $(echo "$score > 0.35" | bc -l) )); then
          echo "Test passed with score $score!"
        else
          echo "Test failed with score $score."
          exit 1
        fi