name: Train

on: 
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags:  tejaswijosyula/cicdassignment:latest

  test:
    needs: train
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Pull and run the Docker image, check for score
      run: |
        score=$(docker run tejaswijosyula/cicdassignment:latest | tail -n 1)
        echo "Score output: $score"
        # The last line of our output and is our score
        if (( $(echo "$score > 0.35" | bc -l) )); then
          echo "Test passed with score $score!"
        else
          echo "Test failed with score $score."
          exit 1
        fi    
