name: Test

on: 
  workflow_run:
    workflows: ["Train"]
    branches: [main]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the Docker image from Docker Hub
      run: docker pull tejaswijosyula/cicdassignment
    
    - name: Run the Docker container
      id: test
      run: docker run tejaswijosyula/cicdassignment

    - name: Check test results
      run: |
        if [ "${{ steps.test.outputs.score }}" > 0.35 ]; then
          echo "Test passed!"
        else
          echo "Test failed."
          exit 1
        fi